# Generated by Django 4.2.13 on 2024-06-10 21:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('episode_id', models.CharField(max_length=20)),
                ('opening_crawl', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=20)),
                ('producer', models.CharField(max_length=20)),
                ('release_date', models.CharField(max_length=20)),
                ('external_reference', models.IntegerField(max_length=10)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('rotation_period', models.CharField(max_length=20)),
                ('orbital_period', models.CharField(max_length=20)),
                ('diameter', models.CharField(max_length=20)),
                ('climate', models.CharField(max_length=20)),
                ('gravity', models.CharField(max_length=20)),
                ('terrain', models.CharField(max_length=20)),
                ('surface_water', models.CharField(max_length=20)),
                ('population', models.CharField(max_length=20)),
                ('external_reference', models.IntegerField(max_length=10)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=10)),
                ('mass', models.CharField(max_length=10)),
                ('hair_color', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=10)),
                ('img', models.URLField(blank=True, null=True)),
                ('films', models.ManyToManyField(related_name='films', to='core.films')),
                ('homeworld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planet', to='core.planets')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
