# Generated by Django 4.2.13 on 2024-06-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='external_reference',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='planets',
            name='external_reference',
            field=models.IntegerField(),
        ),
    ]
