# Generated by Django 4.2.13 on 2024-06-10 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_films_release_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Films',
            new_name='Film',
        ),
        migrations.RenameModel(
            old_name='Planets',
            new_name='Planet',
        ),
    ]
