# Generated by Django 4.2.13 on 2024-06-10 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_films_film_rename_planets_planet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='films',
            field=models.ManyToManyField(null=True, related_name='films', to='core.film'),
        ),
        migrations.AlterField(
            model_name='people',
            name='homeworld',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planet', to='core.planet'),
        ),
    ]
